# Stage 1: Build React app
FROM node:18-alpine as build
WORKDIR /app

# Copy dependencies file and install
COPY package*.json ./
RUN npm install

# Copy source code and build
COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Hapus config default Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copy hasil build React ke folder html Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Tambahkan custom Nginx config untuk SPA + API proxy
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
