services:
  backend:
    build: ./backend
    container_name: backend_dispo
    restart: always

    env_file:
      - ./backend/.env
    environment:
      CORS_ORIGINS: https://dispo.sman1ketapang.sch.id,http://dispo.sman1ketapang.sch.id,http://localhost:3000
      FORWARDED_ALLOW_IPS: "*"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend/storage:/app/storage
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend_dispo
    restart: always
    depends_on:
      - backend
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge



